Talend/camel-karaf

platforms/karaf/features/src/main/resources/features.xml, pom.xml
Fix for https://jira.talendforge.org/browse/TPRUN-4138
There is no `camel-google-pubsub` and `camel-grpc` karaf features available anymore with Camel 3. It would be nice to have OSGi-ready features back for this version.
It has been fixed in Apache Camel/Camel Karaf in 3.18.2 (cf https://issues.apache.org/jira/browse/CAMEL-18344) but we would need a backport in our internal branch.
* Add the missing features
* Ensure that the versions used are only scoped to those specific components
=> TPRUN-4138 Supporting camel-google-pubsub and camel-grpc OSGi deployment

platforms/karaf/features/src/main/resources/features.xml, pom.xml
**What is the problem this PR is trying to solve?**
camel sprint redis feature does not start
**What is the chosen solution to this problem?**
Add missing dependency to the camel netty feature
mvn:io.netty/netty-transport-classes-epoll
**Impacts**
* **components**
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TPRUN-4497
Close detail ( T )
**Please check if the PR fulfills these requirements**
=> fix(TPRUN-4497) fix camel sprint redis startup

platforms/karaf/features/src/main/resources/features.xml, pom.xml
CVE-2022-41966 Xstream to 1.4.20
CVE-2023-1430 Jettison to 1.5.4
CVE-2023-1370 json-smart to 2.4.9
=> TPRUN-5600 TPRUN-5629 TPRUN-5630 Updates of vulnerable dependencies.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
🏁 **Context**
- [TPRUN-6049](https://jira.talendforge.org/browse/TPRUN-6049)
- Fix in release notes: https://github.com/google/guava/releases
In Guava 30, the .createTempDir() method was declared as deprecated without addressing the vulnerability (it was only rectified in the latest release, 32.0.1-jre). Currently, some databases still identify Guava 30 as a CVE.
Bump-up guava version
🎾 **Impacts**
=> fix(TPRUN-6049) guava .createTempDir() vulnerability | CVE-2020-8908

platforms/karaf/features/src/main/resources/features.xml, pom.xml
🏁 **Context**
- [TPRUN-6290](https://jira.talendforge.org/browse/TPRUN-6290)
BouncyCastle<1.74 doesn't check the X.500 name of any certificate, subject, or issuer being passed in for LDAP wild cards which can lead to LDAP injections
Bump-up bouncycastle version
🎾 **Impacts**
=> fix(TPRUN-6290) bcprov-jdk15on:1.69 | CVE-2023-33201

pom.xml
All security updates:
TPRUN-6836 - CVE-2023-36478 - jetty: 9.4.52.v20230823 -> 9.4.53.v20231009
TPRUN-6837 - CVE-2023-36478 - netty: 4.1.94.Final -> 4.1.100.Final
TPRUN-6854 - CVE-2023-44981 - zookeeper: 3.7.1 -> 3.7.2
=> TPRUN-6836 jetty security update to version 9.4.53.v20231009.

tests/camel-integration-test/pom.xml, tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelComponent.java, tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelKarafITest.java, tests/components/camel-jetty/pom.xml, tests/components/camel-jetty/src/main/java/org/apache/karaf/camel/test/CamelJettyComponent.java, tests/components/camel-jetty/src/test/java/org/apache/karaf/camel/itests/CamelJettyITest.java, tests/components/pom.xml
A new implementation of jetty integration test with random port + mock
=> Add camel jetty integration test

components/camel-cxf/camel-cxf-all/pom.xml, components/camel-cxf/camel-cxf-blueprint/pom.xml
Missing an import to jettison :
These are now optionals: 
```
org.codehaus.jettison;resolution:=optional,
org.codehaus.jettison.badgerfish;resolution:=optional,
org.codehaus.jettison.json;resolution:=optional,
org.codehaus.jettison.mapped;resolution:=optional,
org.codehaus.jettison.util;resolution:=optional,
```
+ fix version in camel-cxf-blueprint
=> fix(DPE-586) : add missing import to cxf all

platforms/karaf/features/src/main/resources/features.xml, pom.xml
kudu-client 1.17.0 -> 1.17.1 - CVE-2024-7254(protobuf) CVE-2024-29025(netty) CVE-2023-44487(netty) CVE-2023-47535(netty)
protobuf 3.21.12 -> 3.25.5 - CVE-2024-7254
velocity-engine-core 2.3 -> 2.4.1 - CVE-2024-47554(commons-io)
netty 4.1.111.Final -> 4.1.115.Final - CVE-2024-47535
reactor-netty 1.0.23 -> 1.0.39 - CVE-2023-34054 CVE-2023-34062 CVE-2022-31684
mina 2.1.6,2.1.8 -> 2.1.10 - CVE-2024-52046
async-http-client 2.12.3 -> 2.12.4 - CVE-2024-53990
jetty 9.4.55.v20240627 -> 9.4.56.v20240826 - CVE-2024-8184
=> DPE-571 Security updates.

platforms/karaf/features/pom.xml, platforms/karaf/features/src/main/resources/features.xml, pom.xml
🏁 **Context**
- [DPE-420](https://qlik-dev.atlassian.net/browse/DPE-420)
Cannot run route using camel-sqs, because of missing file in the META-INF of the service mix jar
Remove usage of servicemix, use wrap protocol instead.
🎾 **Impacts**
All aws features are impacted
[DPE-369]: https://qlik-dev.atlassian.net/browse/DPE-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-420]: https://qlik-dev.atlassian.net/browse/DPE-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-420) : remove usage of aws servicemix

features/src/main/feature/camel-features.xml, tests/features/camel-aws2-kinesis/pom.xml, tests/features/camel-aws2-kinesis/src/main/java/org/apache/karaf/camel/test/CamelAws2KinesisRouteSupplier.java, tests/features/camel-aws2-kinesis/src/test/java/org/apache/karaf/camel/itest/CamelAws2KinesisITest.java, tests/features/pom.xml
🏁 **Context**
- [DPE-562](https://qlik-dev.atlassian.net/browse/DPE-562)
Class not found exception
Add missing dependencies to aws kinesis feature
🎾 **Impacts**
Only aws kinesis feature is impacted
[DPE-562]: https://qlik-dev.atlassian.net/browse/DPE-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-562): Add an integration test for AWS Kinesis

features/src/main/feature/camel-features.xml
🏁 **Context**
- [DPE-562](https://qlik-dev.atlassian.net/browse/DPE-562)
the last change breaks the build https://jenkins-esb.datapwn.com/job/camel-karaf/job/tesb%252Fcamel-karaf-4.8.1.x/13/
Set properly the version of the bundle camel-aws2-kinesis
🎾 **Impacts**
Only aws kinesis feature is impacted
[DPE-562]: https://qlik-dev.atlassian.net/browse/DPE-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-562): Properly set the version of camel-aws2-kinesis

features/src/main/feature/camel-features.xml
🏁 **Context**
- [DPE-642](https://qlik-dev.atlassian.net/browse/DPE-642)
The test assumes that groovy-json is pre-installed like in 3.20.9
Add the same subprojects of groovy to camel-groovy like in 3.20.9 for consistency
🎾 **Impacts**
[DPE-642]: https://qlik-dev.atlassian.net/browse/DPE-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-642): Add Groovy subprojects to camel-groovy

Jenkinsfile.talend, components/camel-vm/pom.xml, features/src/main/feature/camel-features.xml, pom.xml
🏁 **Context**
- [DPE-643](https://qlik-dev.atlassian.net/browse/DPE-643)
The wrapper camel-vm has been modified so it needs to be part of the custom modules
Add camel-vm to custom modules
🎾 **Impacts**
[DPE-643]: https://qlik-dev-sandbox-345.atlassian.net/browse/DPE-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-643): Add camel-vm to custom modules

features/src/main/feature/camel-features.xml, pom.xml
CVE-2024-47535  netty 4.1.112 -> 4.1.115
CVE-2024-8184  jetty 9.4.54.v20240208 -> 9.4.57.v20241219
CVE-2023-3635  okio 1.17.5 -> 1.17.6
CVE-2024-28168  fop-core 2.9 -> 2.10
CVE-2025-23026  jte-runtime 3.1.12 -> 3.1.16
CVE-2024-38827  spring-security  6.3.3 -> 6.3.6
CVE-2024-47535  couchbase-client 3.7.2 -> 3.7.7 (embedded netty)
=> DPE-712 Secuirty updates of dependencies.

platforms/karaf/features/src/main/resources/features.xml, pom.xml
🏁 **Context**
- [DPE-501](https://qlik-dev.atlassian.net/browse/DPE-501)
`Reason: java.io.IOException: Transport scheme NOT recognized`
`reason: java.io.IOException: Service not found: 'META-INF/services/org/apache/activemq/wireformat/default'`
When the `activemq-osgi` bundle is updated, the references to the services it provides are lost: https://stackoverflow.com/questions/22987656/transport-scheme-not-recognized-tcp.
Remove the unnecessary wrap protocol on the bundle and declare the bundle as `dependency` where needed.
🎾 **Impacts**
[DPE-501]: https://qlik-dev.atlassian.net/browse/DPE-501?atlOrigin=eyJpIjoiNWRkN …
=> DPE-501: avoid unnecessary updates of activemq-osgi

pom.xml
CVE-2025-27636 - backport of fix from Camel 4.8.5.
=> DPE-852 Fix DefaultHeaderFilterStrategy lowercase filtering.

features/src/main/feature/camel-features.xml, pom.xml
🏁 **Context**
- [DPE-883](https://qlik-dev.atlassian.net/browse/DPE-883)
`camel-azure-event-hubs` component is missing runtime dependencies
Add missing dependencies
🎾 **Impacts**
[DPE-883]: https://qlik-dev-sandbox-345.atlassian.net/browse/DPE-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DPE-883: add missing dependencies for azure-eventhubs

Jenkinsfile.talend, components/camel-platform-http-jolokia/pom.xml, features/src/main/feature/camel-features.xml, pom.xml
🏁 **Context**
- [DPE-903](https://qlik-dev.atlassian.net/browse/DPE-903)
Avoid having multiple Jolokia versions in the final ESB Runtime build
Aling Jolokia version with Karaf
🎾 **Impacts**
[DPE-903]: https://qlik-dev-sandbox-345.atlassian.net/browse/DPE-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DPE-903: aling Jolokia version with Karaf

features/src/main/feature/camel-features.xml, pom.xml
CVE-2025-52999 hazelcast 5.4.0 -> 5.5.0 (embedded Jackson core 2.14.2 -> 2.17.2) CVE-2025-49146 postgresql jdbc driver 42.7.4 -> 42.7.7 CVE-2024-1233 disable camel-elytron (deprecated fro removal by camel)
=> DPE-1481 Security fixes.

features/src/main/feature/camel-features.xml
🏁 **Context**
- [DPE-1315](https://qlik-dev.atlassian.net/browse/DPE-1315)
During patch, zookeeper has only optional Import on netty, so the refresh does not happen correctly
Enforce netty import so that refresh is correctly done
🎾 **Impacts**
[DPE-1704]: https://qlik-dev.atlassian.net/browse/DPE-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1315]: https://qlik-dev.atlassian.net/browse/DPE-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DPE-1315): force netty resolution
